### ISSUE TITLE
Comments inside record not properly highlight

### ISSUE THREAD

**Issue by colljori** [Entomy/Ada-vscode#11]
The comments inside a record clause is not highlighted the same way others comments are.

![IssueVscodeAdaEntomy](https://user-images.githubusercontent.com/23013840/56347167-06f95a80-61c4-11e9-8345-bd95fe548430.PNG)

**Comment by Entomy** [comment]
![image](https://user-images.githubusercontent.com/25399505/56363030-3eaed500-61b9-11e9-980e-6b446e948a39.png)

Fixed
