### ISSUE TITLE
`End` statement for defined operators being recognized as a string, not as an entity name

### ISSUE THREAD

**Issue by fxcqz** [Entomy/Ada-vscode#2]
Just in the definition of the operator itself.

![ada](https://user-images.githubusercontent.com/2554158/37681929-fa4da522-2c7f-11e8-808f-aae790dbf865.png)

**Comment by Entomy** [comment]
Should be fixed, reopen if necessary

![capture](https://user-images.githubusercontent.com/25399505/37682545-47235cf4-2c60-11e8-8bf4-c0522f83e404.JPG)
