### ISSUE TITLE
Strange highlighting between `with` keyword and a semicolon in aspect specifications

### ISSUE THREAD

**Issue by wtok** [Entomy/Ada-vscode#20]
It seems everything between `with` and a semicolon `;` is highlighted a certain way, which causes strange highlighting when specifying aspects.

When there's only one aspect on the line, literals and such aren't highlighted correctly.
When there's multiple lines, everything looks okay, but comments aren't highlighted correctly.

![image](https://user-images.githubusercontent.com/10289860/57365354-08ff7980-71c4-11e9-9b74-4f4f07a068a0.png)

Code snippet for testing:

```ada
   -- This seems to be okay:
   type T is new Integer with Static_Predicate => T /= 5,
                              Atomic => True; 

   -- In this one, Static_Predicate and 5 aren't highlighted correctly: 
   type T is new Integer with Static_Predicate => T /= 5;

   -- When a comment appears in between multiple aspects, it's not highlighted 
   -- correctly:
   type T is new Integer with Static_Predicate => T /= 5,
                              -- Some explanatory comment
                              Atomic => True; 

   -- Applies to functions and such, too:
   function Thing (Arg : in T) return Thing_Type
      with Pre => Arg /= 500, 
           -- Here is a comment, which isn't highlighted correctly.
           Depends => (Thing'Result => Arg);

   function Thing2 return Thing_Type
      with Pre => Arg /= 500; -- The literal `500` isn't highlighted correctly.
```

**Comment by Entomy** [comment]
So apparently the regex engine VS Code uses is quite sophisticated and can handle this. I've been working on a rewrite using much more sophisticated approaches based on some things I've learned about it.

I still need to figure things out, but you can see it's recognizing sections much more appropriately, even if there's line breaks.

However this won't be pushed to the VS Code Marketplace until I meet feature parity with the older version.

![image](https://user-images.githubusercontent.com/25399505/60271587-a2900100-98c0-11e9-978a-c3497524c4b1.png)

**Comment by wtok** [comment]
Good to hear! Much appreciated.
