### ISSUE TITLE
Numbers in identifiers are highlighted as number literals

### ISSUE THREAD

**Issue by wtok** [Entomy/Ada-vscode#4]
Screenshot demonstrates it best:

![screenshot from 2018-07-12 00-52-18](https://user-images.githubusercontent.com/10289860/42582280-e10e0010-856d-11e8-901e-b2d1e2a65794.png)

You can see that `Matrix4` and such are highlighted properly, but `Identity4` and such are not.

**Comment by Entomy** [comment]
Should be fixed, reopen if necessary

![image](https://user-images.githubusercontent.com/25399505/42609997-62b046c0-855d-11e8-9253-37a09d4eb25a.png)
