### ISSUE TITLE
comments

### ISSUE THREAD

**Issue by joeamnesiac** [Entomy/Ada-vscode#5]
comments ( -- ) are hightlighted correctly, but a double comments ( -- -- ) appear as code rather than comments. The presence of ( -- ) should make the rest of that line a comment.
![capture](https://user-images.githubusercontent.com/18572906/46804426-73e5f080-cd5a-11e8-8a8b-f0af54353969.PNG)

**Comment by Entomy** [comment]
![image](https://user-images.githubusercontent.com/25399505/46831187-ab5f9780-cd70-11e8-8b71-b33803990e4a.png)
