### ISSUE TITLE
Add support for .ada extension

### ISSUE THREAD

**Issue by Xynth22** [Entomy/Ada-vscode#6]
Many Ada projects I have worked on use the generic .ADA extension instead of separate .adb and .ads extensions. It would be nice if we could get the same highlighting to work on the .ada extension.

**Comment by Xynth22** [comment]
I made the change and was able to package it into a vsix and test it. Your repo doesn't allow me to add branches/pull request so I will use this change and be more than happy to provide it to you (it is, as I'm sure you know, fairly trivial.)

**Comment by Entomy** [comment]
I'm not sure why it's not letting you create a pull request, as this isn't something I've ever disabled, and I've received pull requests before for this repo. You are somewhat correct about it being more complicated than just adding `*.ada` to the `package.json`. It is trivial though, just requires a few other additions. I'll get it done.

**Comment by Xynth22** [comment]
Yeah, when I select your branches dialog it only lets me filter:

![image](https://user-images.githubusercontent.com/31621879/47399914-83711c00-d700-11e8-9627-6e69d6480cd4.png)

 whereas other repos let me also create:
![image](https://user-images.githubusercontent.com/31621879/47399952-b3202400-d700-11e8-870b-76bffb1aef90.png)

**Comment by Entomy** [comment]
Should be fixed. Reopen if necessary.
