### ISSUE TITLE
Comments on code lines that end in semicolons are highlighted as code

### ISSUE THREAD

**Issue by wtok** [Entomy/Ada-vscode#7]
![image](https://user-images.githubusercontent.com/10289860/55764068-1f24f780-5aa9-11e9-8da3-657687e21f90.png)

**Comment by Entomy** [comment]
![image](https://user-images.githubusercontent.com/25399505/55766939-d89db180-5a44-11e9-8956-82b06aa5000b.png)

Should be fixed, reopen if necessary

**Comment by wtok** [comment]
Thanks!

**Comment by Entomy** [comment]
Absolutely, thanks for letting me know.
